module PresetStarts (blinker, gliderGun, pulsar, bigPulsar, toroidalGliders) where

import GameOfLife exposing (..)

--taken from wikipedia

blinker = fromListList [[False, True, False], [False, True, False], [False, True, False]]

gliderGun = fromListList [
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True,  True,  False, False, False, False, False, False],
        [False, False, False, False, False, True,  True,  False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],

        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],

        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True,  True,  True,  False, False, False, False, False],
        [False, False, False, False, True,  False, False, False, True,  False, False, False, False],
        [False, False, False, True,  False, False, False, False, False, True,  False, False, False],
        [False, False, False, True,  False, False, False, False, False, True,  False, False, False],

        [False, False, False, False, False, False, True,  False, False, False, False, False, False],
        [False, False, False, False, True,  False, False, False, True,  False, False, False, False],
        [False, False, False, False, False, True,  True,  True,  False, False, False, False, False],
        [False, False, False, False, False, False, True,  False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],

        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, True,  True,  True,  False, False, False, False, False, False, False],
        [False, False, False, True,  True,  True,  False, False, False, False, False, False, False],
        [False, False, True,  False, False, False, True,  False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],

        [False, True,  True,  False, False, False, True,  True,  False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, True,  True,  False, False, False, False, False, False, False, False],
        [False, False, False, True,  True,  False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False]

    ]

pulsar = fromListList [
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],    
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    ]
bigPulsar = fromListList [
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],    
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], 
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],    
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],

        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], 
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],    
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False],
        [False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],        
        [False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    ]

toroidalGliders = fromListList [
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, True, False, False, False, False, True, False, False],
        [False, False, False, True, False, False, False, False, True, False],
        [False, True, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, True, False, False, False, False, True, False, False],
        [False, False, False, True, False, False, False, False, True, False],
        [False, True, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, True, False, False, False, False, True, False, False],
        [False, False, False, True, False, False, False, False, True, False],
        [False, True, True, True, False, False, True, True, True, False],
        [False, False, False, False, False, False, False, False, False, False]
    ]